safe: false
markdown: redcarpet
pygments: true
permalink: pretty
baseurl: /
plugins: ./_plugins
future: true
lsi: true
exclude: ["Gruntfile.js", "README.MD", "LICENSE", "styl/", "node_modules/", "bower_components/"]

redcarpet:
  extensions: [smart]

name: Nick Nisi
url: http://nicknisi.com
description: My Blog
username: nicknisi
